# Generated by Django 4.0.1 on 2022-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True)),
                ('biography', models.TextField(blank=True, max_length=400)),
                ('awards', models.ManyToManyField(blank=True, related_name='recipients', to='awards.Award')),
            ],
        ),
    ]
