# Generated by Django 4.0.2 on 2022-02-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('biography', models.TextField(max_length=1200)),
                ('url_name', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
