# Generated by Django 4.0.1 on 2022-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performer",
            name="biography",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="performer",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
