# Generated by Django 4.0.1 on 2022-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0005_alter_performer_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='biography',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
