# Generated by Django 4.0.1 on 2022-02-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performers", "0006_alter_performer_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performer",
            name="biography",
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name="performer",
            name="birthdate",
            field=models.DateField(),
        ),
    ]
