# Generated by Django 4.0.2 on 2022-02-25 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_of_release', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1888)])),
                ('synopsis', models.TextField(max_length=1200)),
                ('url_name', models.SlugField(blank=True, max_length=51, null=True, unique=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='starred_in', to='performers.Performer')),
                ('director', models.ManyToManyField(blank=True, related_name='directed', to='performers.Performer')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url_name', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=50)),
                ('written_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=500)),
                ('url_name', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='users.userprofile')),
                ('film_reviewed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='films', to='movies.Genre'),
        ),
    ]
