# Generated by Django 4.0.1 on 2022-01-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='films', to='performers.Performer'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='performers.performer'),
        ),
    ]
