# Generated by Django 4.0.1 on 2022-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_film_year_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='url_name',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
