# Generated by Django 4.0.1 on 2022-02-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0005_alter_performer_url_name'),
        ('movies', '0006_alter_film_year_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='starred_in', to='performers.Performer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directed', to='performers.performer'),
        ),
    ]
