# Generated by Django 4.0.1 on 2022-02-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_alter_film_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="films", to="movies.Genre"
            ),
        ),
    ]
