# Generated by Django 4.0.1 on 2022-02-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmreview',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
