# Generated by Django 4.0.1 on 2022-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_filmreview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='movies.Genre'),
        ),
    ]
