# Generated by Django 4.0.1 on 2022-02-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_filmreview_film_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmreview',
            name='film_reviewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.film'),
        ),
    ]
