# Generated by Django 4.0.1 on 2022-02-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0023_remove_film_director_film_director_alter_film_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmreview",
            name="film_reviewed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies.film",
            ),
        ),
    ]
