# Generated by Django 4.0.2 on 2022-02-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_established', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('url_name', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmAwardReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField()),
                ('award_status', models.CharField(choices=[('winner', 'winner'), ('nominee', 'nominee')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('url_name', models.SlugField(blank=True, null=True, unique=True)),
                ('awarded_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.film')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.filmaward')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='performers.performer')),
            ],
        ),
    ]
