# Generated by Django 4.0.1 on 2022-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_established', models.DateField(blank=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
