# Generated by Django 4.0.1 on 2022-01-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_established', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FilmAwardReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField()),
                ('awarded_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.film')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performers.performer')),
            ],
        ),
    ]
