# Generated by Django 4.0.1 on 2022-01-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmawardreceived",
            name="type",
            field=models.CharField(choices=[], max_length=50, null=True),
        ),
    ]
