# Generated by Django 4.0.1 on 2022-02-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
        ('awards', '0003_alter_filmaward_name_alter_filmawardreceived_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmawardreceived',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='performers.performer'),
        ),
    ]
