# Generated by Django 4.0.1 on 2022-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0004_alter_filmawardreceived_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmaward",
            name="url_name",
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
