# Generated by Django 4.0.1 on 2022-02-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_filmaward_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmawardreceived',
            name='type',
        ),
        migrations.AddField(
            model_name='filmawardreceived',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.filmaward'),
        ),
        migrations.AddField(
            model_name='filmawardreceived',
            name='url_name',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filmaward',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filmaward',
            name='url_name',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
