# Generated by Django 4.0.1 on 2022-02-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performers", "0006_alter_performer_biography"),
        ("awards", "0008_filmawardreceived_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmawardreceived",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="performers.performer",
            ),
        ),
    ]
