# Generated by Django 4.0.1 on 2022-02-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_film_genre'),
        ('awards', '0009_alter_filmawardreceived_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmawardreceived',
            name='awarded_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.film'),
        ),
    ]
