# Generated by Django 4.0.1 on 2022-02-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performers", "0006_alter_performer_biography"),
        ("movies", "0015_alter_filmreview_content"),
        ("awards", "0012_rename_type_filmawardreceived_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmaward",
            name="name",
            field=models.CharField(default="award", max_length=50),
        ),
        migrations.AlterField(
            model_name="filmawardreceived",
            name="award_status",
            field=models.CharField(
                choices=[("winner", "winner"), ("nominee", "nominee")],
                default="winner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="filmawardreceived",
            name="awarded_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movies.film",
            ),
        ),
        migrations.AlterField(
            model_name="filmawardreceived",
            name="category",
            field=models.CharField(default="category", max_length=50),
        ),
        migrations.AlterField(
            model_name="filmawardreceived",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="performers.performer",
            ),
        ),
    ]
